# Generated by Django 5.2.4 on 2025-07-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_remove_publisher_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
