# Generated by Django 5.2.4 on 2025-07-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_remove_developer_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
