# Generated by Django 5.2.4 on 2025-07-24 10:01

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('logo', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('logo', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('fighting', 'Fighting'), ('first-person shooter', 'First-Person Shooter'), ('horror', 'Horror'), ('indie', 'Indie'), ('platformer', 'Platformer'), ('puzzle', 'Puzzle'), ('racing', 'Racing'), ('role-playing', 'Role-Playing'), ('rpg', 'RPG'), ('shooter', 'Shooter'), ('simulation', 'Simulation'), ('sports', 'Sports'), ('strategy', 'Strategy')], max_length=20)),
                ('console', models.CharField(choices=[('Playstation', 'Playstation'), ('Playstation 2', 'Playstation 2'), ('Playstation 3', 'Playstation 3'), ('Playstation 4', 'Playstation 4'), ('Playstation 5', 'Playstation 5'), ('Nintendo 64', 'Nintendo 64'), ('Nintendo GameCube', 'Nintendo GameCube'), ('Nintendo Wii', 'Nintendo Wii'), ('Nintendo Wii U', 'Nintendo Wii U'), ('Nintendo Switch', 'Nintendo Switch'), ('Nintendo Switch 2', 'Nintendo Switch 2'), ('Xbox', 'Xbox'), ('Xbox 360', 'Xbox 360'), ('Xbox One', 'Xbox One'), ('Xbox Series X', 'Xbox Series X'), ('PC', 'PC'), ('Other', 'Other')], default='PC', max_length=50)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('review_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('review_text', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='reviews.developer')),
                ('likes', models.ManyToManyField(blank=True, related_name='game_likes', to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.publisher')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-created_on'],
            },
        ),
    ]
