# Generated by Django 5.2.4 on 2025-07-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='console',
        ),
        migrations.RemoveField(
            model_name='review',
            name='genre',
        ),
    ]
