# Generated by Django 5.2.4 on 2025-07-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Review',
            new_name='review',
        ),
    ]
